name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Config
      run: git config --global url."https://api:${{secrets.GH_ACCESS_TOKEN}}@github.com/".insteadOf "https://github.com/"
    - name: Check format
      run: CARGO_NET_GIT_FETCH_WITH_CLI=true cargo fmt -- --check
